# Generated by Django 2.2.6 on 2019-12-08 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='Title')),
                ('descriptions', models.TextField(verbose_name='Summary')),
                ('content', models.TextField(verbose_name='Full content')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 8, 21, 24, 56, 163302), verbose_name='Publiced')),
            ],
            options={
                'verbose_name': "blog's article",
                'verbose_name_plural': "blog's articles",
                'db_table': 'Posts',
                'ordering': ['-posted'],
            },
        ),
    ]
