# Generated by Django 2.2.6 on 2019-12-15 18:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20191209_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 15, 21, 54, 9, 296991), verbose_name='Publiced'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 15, 21, 54, 9, 296991), verbose_name='Date')),
                ('post', models.TextField(verbose_name='Comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments of blog\\s articles',
                'db_table': 'Comments',
                'ordering': ['-date'],
            },
        ),
    ]
